version: 2
jobs:
  build-linux:
    docker:
      - image: openjdk:8-jdk-slim
    steps:
      - checkout
      - restore_cache:
          key: testmints-linux-cache-1-{{ .Branch }}
      - run: "./gradlew check publishToMavenLocal"
      - save_cache:
          key: testmints-linux-cache-1-{{ .Branch }}
          paths:
            - "~/.gradle"
            - ".gradle"
      - store_artifacts:
          path: build/test-output
      - store_test_results:
          path: build/test-output
      - persist_to_workspace:
          root: ./
          paths:
            - "*"
#  build-mac:
#    macos:
#      xcode: "10.1.0"
#    steps:
#      - checkout
#      - restore_cache:
#          key: testmints-mac-cache-1-{{ .Branch }}
#      - run: "./gradlew check publishToMavenLocal"
#      - save_cache:
#          key: testmints-mac-cache-1-{{ .Branch }}
#          paths:
#            - "~/.gradle"
#            - ".gradle"
#      - store_artifacts:
#          path: build/test-output
#      - store_test_results:
#          path: build/test-output
#      - persist_to_workspace:
#          root: ./
#          paths:
#            - "*"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-linux
#      - build-mac